# config server port:
server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./zcconfig-repo, file:../zcconfig-repo, file:../../zcconfig-repo, file:../../../zcconfig-repo, file:../../../../zcconfig-repo, file:../../../../../zcconfig-repo